spring.application.name=prj_Job_and_Recruitment_Exchange_System
#Config datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_prj_Job_and_Recruitment_Exchange_System?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
#Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#Config JWT
jwt-secret = chuoibimatdemahoachuoijwtdudaidetangbaomat
#Chuỗi jwt được tạo ra sẽ tồn tại trong 20'
jwt-expire = 1200000

#Chuỗi jwt được tạo ra sẽ tồn tại trong 2'
#jwt-expire = 120000
#refresh token sẽ tồn tại trong 30 ngày
jwt-refresh-expire = 2592000000